### ISSUE TITLE
rtl layout is off

### ISSUE THREAD

**Issue by mustafa0x** [wobsoriano/svelte-sonner#52]
Thanks for this!

### Describe the bug

![image](https://github.com/wobsoriano/svelte-sonner/assets/1473102/2bf6e51a-99f0-4aaf-8700-47c4a6dcb26e)

### Reproduction

https://svelte.dev/repl/dd99838096384c3ba0f48301042dff97?version=4.2.9

### System Info

```bash
svelte repl
```

### Severity

annoyance

**Comment by mustafa0x** [comment]
this helped.

```css
ol[data-sonner-toaster] {
    right: 1rem !important;
    font-family: inherit;

    & [data-sonner-toast] [data-icon] {
        margin-left: 0.2rem;
        margin-right: unset;
    }
}
```
